import type { Metadata } from 'next'
import PageLayout, { H1, Lede, H2, P } from '@/components/PageLayout'
import { pageMetadata, articleLd } from '@/lib/seo'

const PATH = '/terms'
const TITLE = 'Terms of Use — AI Companions Labs'
const DESC = 'Terms of use for AI Companions Labs, an 18+ AI companion discovery platform.'

export const metadata: Metadata = pageMetadata({ title: TITLE, description: DESC, path: PATH })

export default function TermsPage() {
  return (
    <PageLayout
      crumbs={[{ name: 'Home', path: '/' }, { name: 'Terms', path: PATH }]}
      jsonLd={articleLd({ headline: TITLE, description: DESC, path: PATH })}
    >
      <H1>Terms of Use</H1>
      <Lede>
        By using AI Companions Labs you confirm that you are at least 18 years old and agree to
        the following.
      </Lede>

      <H2>18+ only</H2>
      <P>
        This is an adult-oriented site. All characters shown are fictional, AI-generated adults.
        See our <a href="/18-plus/">18+ notice</a> for details.
      </P>

      <H2>No professional advice</H2>
      <P>
        AI Companions Labs publishes editorial opinion and reviews. Nothing on this site is
        professional psychological, medical or legal advice. AI companions can be entertaining and
        useful, but they are not a substitute for human connection or professional support.
      </P>

      <H2>Third-party platforms</H2>
      <P>
        When you click through to a third-party platform (including Secret Desires and any other
        reviewed service), you are subject to that platform&apos;s own terms of service and privacy
        policy. We are not responsible for how any third-party platform bills, moderates, or
        stores data.
      </P>

      <H2>Content</H2>
      <P>
        All original content on this site — articles, character profiles, images generated by us —
        is © AI Companions Labs unless noted otherwise. You may quote short excerpts with
        attribution. Do not republish characters, galleries or full articles without permission.
      </P>

      <H2>Changes</H2>
      <P>Terms may be updated. Material changes are noted with a date.</P>
    </PageLayout>
  )
}
